# Generated by Django 5.0 on 2025-07-02 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Birlikning nomi')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Birlikning kodi')),
            ],
            options={
                'verbose_name': 'Birlik',
                'verbose_name_plural': 'Birliklar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('name', models.CharField(max_length=400, unique=True, verbose_name='Kategoriyaning nomi')),
                ('name_ru', models.CharField(blank=True, max_length=400, null=True, unique=True, verbose_name='Kategoriyaning nomi (Ruscha)')),
                ('number', models.IntegerField(default=0, verbose_name='Kategoriyaning tartib raqami')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kategoriyaning kodi')),
                ('top', models.IntegerField(default=0, verbose_name='Yuqori')),
                ('bottom', models.IntegerField(default=0, verbose_name='Quyi')),
                ('rasfas', models.BooleanField(default=False, verbose_name='Rasfas')),
                ('is_weekly', models.BooleanField(default=False, verbose_name='Haftalik')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='form.birlik', verbose_name='Birlik')),
            ],
            options={
                'verbose_name': 'Mahsulot Kategoriyasi',
                'verbose_name_plural': 'Mahsulot Kategoriyalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('name', models.CharField(max_length=400, unique=True, verbose_name='Mahsulotning nomi')),
                ('name_ru', models.CharField(blank=True, max_length=400, null=True, unique=True, verbose_name='Mahsulotning nomi (Ruscha)')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mahsulot kodi')),
                ('price', models.FloatField(default=0.0, verbose_name='Narxi')),
                ('unit', models.CharField(default='kg', max_length=50, verbose_name="O'lchov birligi")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='form.productcategory', verbose_name='Kategoriyasi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TochkaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('last_price', models.FloatField(default=0.0, verbose_name='Oxirgi Narxi')),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.tochka', verbose_name='Hudud')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huds', to='form.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot Hudud',
                'verbose_name_plural': 'Mahsulot Hududlar',
                'ordering': ['product__name', 'hudud__name'],
            },
        ),
        migrations.CreateModel(
            name='TochkaProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('price', models.FloatField(default=0.0, verbose_name='Narxi')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Tekshirilgan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='home.employee', verbose_name='Xodim')),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='home.tochka', verbose_name='Hudud')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='home.period', verbose_name='Davr')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='form.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot Narx Tarixi',
                'verbose_name_plural': 'Mahsulot Narx Tarixlari',
                'ordering': ['product__name', 'hudud__name', '-created_at'],
            },
        ),
    ]
