# Generated by Django 5.0 on 2025-07-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='birlik',
            name='miqdor',
            field=models.FloatField(default=0.0, verbose_name='Miqdor'),
        ),
        migrations.AddField(
            model_name='tochkaproducthistory',
            name='unit_miqdor',
            field=models.FloatField(default=0.0, verbose_name='Birlik miqdori'),
        ),
        migrations.AddField(
            model_name='tochkaproducthistory',
            name='unit_price',
            field=models.FloatField(default=0.0, verbose_name='Birlik narxi'),
        ),
    ]
