# Generated by Django 5.0 on 2025-07-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_birlik_miqdor_tochkaproducthistory_unit_miqdor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Mahsulotning nomi'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Kategoriyaning tartib raqami (nt)'),
        ),
    ]
