# Generated by Django 5.0 on 2025-07-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_remove_product_name_ru_alter_product_name_and_more'),
        ('home', '0007_ntochka'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochkaproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='tochkaproduct',
            name='is_udalen',
            field=models.BooleanField(default=True, verbose_name='Udalen'),
        ),
        migrations.AddField(
            model_name='tochkaproduct',
            name='ntochka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.ntochka', verbose_name='Kichik hudud'),
            preserve_default=False,
        ),
    ]
