# Generated by Django 5.0 on 2025-07-07 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_tochkaproduct_is_active_tochkaproduct_is_udalen_and_more'),
        ('home', '0008_tochka_employee_delete_employeetochka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tochkaproducthistory',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='home.perioddate', verbose_name='Davr'),
        ),
    ]
