# Generated by Django 5.0 on 2025-07-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_tochkaproducthistory_period'),
        ('home', '0008_tochka_employee_delete_employeetochka'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tochkaproduct',
            unique_together={('product', 'hudud', 'ntochka')},
        ),
    ]
