# Generated by Django 5.0 on 2025-07-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_alter_tochkaproduct_unique_together'),
        ('home', '0009_ntochka_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='bottom',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='top',
        ),
        migrations.AddField(
            model_name='product',
            name='bottom',
            field=models.IntegerField(default=0, verbose_name='Quyi'),
        ),
        migrations.AddField(
            model_name='product',
            name='top',
            field=models.IntegerField(default=0, verbose_name='Yuqori'),
        ),
        migrations.AlterUniqueTogether(
            name='tochkaproduct',
            unique_together={('product', 'hudud', 'ntochka')},
        ),
    ]
