# Generated by Django 5.0 on 2025-07-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_remove_productcategory_bottom_and_more'),
        ('home', '0010_ntochka_hudud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tochkaproduct',
            options={'ordering': ['product__name'], 'verbose_name': 'Mahsulot Hudud', 'verbose_name_plural': 'Mahsulot Hududlar'},
        ),
        migrations.AlterUniqueTogether(
            name='tochkaproduct',
            unique_together={('product', 'ntochka')},
        ),
        migrations.RemoveField(
            model_name='tochkaproduct',
            name='hudud',
        ),
    ]
