# Generated by Django 5.0 on 2025-07-12 14:37

import apps.form.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_alter_tochkaproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_import',
            field=models.BooleanField(default=True, verbose_name='Import qilingan'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='product_category_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), apps.form.models.validate_file_size], verbose_name='Logo'),
        ),
    ]
