# Generated by Django 5.0 on 2025-07-12 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_product_is_import_productcategory_logo'),
        ('home', '0018_ntochka_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tochkaproducthistory',
            options={'ordering': ['product__name'], 'verbose_name': 'Mahsulot Narx Tarixi', 'verbose_name_plural': 'Mahsulot Narx Tarixlari'},
        ),
        migrations.AddField(
            model_name='tochkaproduct',
            name='hudud',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.tochka', verbose_name='Hudud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tochkaproducthistory',
            name='ntochka',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='home.ntochka', verbose_name='Hudud'),
            preserve_default=False,
        ),
    ]
