# Generated by Django 5.0 on 2025-07-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_alter_tochkaproducthistory_options_and_more'),
        ('home', '0018_ntochka_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochkaproduct',
            name='previous_price',
            field=models.FloatField(default=0.0, verbose_name='Oldingi Narxi'),
        ),
        migrations.AlterUniqueTogether(
            name='tochkaproducthistory',
            unique_together={('product', 'ntochka', 'period')},
        ),
    ]
