# Generated by Django 5.0 on 2025-07-14 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_tochkaproduct_previous_price_and_more'),
        ('home', '0018_ntochka_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tochkaproducthistory',
            name='ntochka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='home.ntochka', verbose_name='Ntochka'),
        ),
    ]
