# Generated by Django 5.0 on 2025-07-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_alter_tochkaproducthistory_ntochka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_import',
            field=models.BooleanField(default=False, verbose_name='Import qilingan'),
        ),
    ]
