# Generated by Django 5.0 on 2025-07-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochkaproducthistory',
            name='status',
            field=models.CharField(choices=[('mavjud', 'Mahsulot mavjud'), ('chegirma', 'Mahsulot chegirma asosida sotilayabdi'), ('mavsumiy', 'Mavjud emas (Mavsumiy mahsulot)'), ('vaqtinchalik', 'Mavjud emas (Vaqtincha mavjud emas)'), ('sotilmayapti', 'Mavjud emas (Mahsulot sotilmayabdi)'), ('obyekt_yopilgan', 'Mavjud emas (Obyekt yopilgan)')], default='mavjud', max_length=15, verbose_name='Status'),
        ),
    ]
