# Generated by Django 5.0 on 2025-07-15 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_tochkaproducthistory_status'),
        ('home', '0019_alter_ntochka_options_alter_tochka_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_import',
            field=models.BooleanField(default=False, verbose_name='Import qilinganmi?'),
        ),
        migrations.AlterField(
            model_name='tochkaproduct',
            name='hudud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.tochka', verbose_name='Obyekt'),
        ),
        migrations.AlterField(
            model_name='tochkaproduct',
            name='ntochka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.ntochka', verbose_name='Rasta'),
        ),
        migrations.AlterField(
            model_name='tochkaproducthistory',
            name='hudud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='home.tochka', verbose_name='Obyekt'),
        ),
        migrations.AlterField(
            model_name='tochkaproducthistory',
            name='ntochka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='home.ntochka', verbose_name='Rasta'),
        ),
    ]
