# Generated by Django 5.0 on 2025-07-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_alter_product_is_import_alter_tochkaproduct_hudud_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tochkaproduct',
            options={'ordering': ['product__name'], 'verbose_name': 'Rasta mahsulot', 'verbose_name_plural': 'Rasta mahsulotlari'},
        ),
        migrations.AlterModelOptions(
            name='tochkaproducthistory',
            options={'ordering': ['product__name'], 'verbose_name': 'Mahsulot marx tarixi', 'verbose_name_plural': 'Mahsulot narxlari tarixi'},
        ),
        migrations.AlterModelTable(
            name='birlik',
            table='birlik',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
        migrations.AlterModelTable(
            name='tochkaproduct',
            table='rasta_product',
        ),
        migrations.AlterModelTable(
            name='tochkaproducthistory',
            table='product_history',
        ),
    ]
