# Generated by Django 5.0 on 2025-07-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0019_alter_tochkaproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tochkaproduct',
            name='is_udalen',
            field=models.BooleanField(default=False, verbose_name='Udalen'),
        ),
    ]
