# Generated by Django 5.0 on 2025-07-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_alter_tochkaproduct_is_udalen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochkaproducthistory',
            name='alternative_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.product', verbose_name='Alternativ Product'),
        ),
        migrations.AddField(
            model_name='tochkaproducthistory',
            name='is_alternative',
            field=models.BooleanField(default=False, verbose_name='Alternativ'),
        ),
    ]
