# Generated by Django 5.0 on 2025-07-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_tochkaproducthistory_alternative_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='is_weekly',
        ),
        migrations.AddField(
            model_name='product',
            name='is_weekly',
            field=models.BooleanField(default=False, verbose_name='Haftalik'),
        ),
    ]
