# Generated by Django 5.0 on 2025-07-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_remove_productcategory_is_weekly_product_is_weekly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='name_ru',
        ),
    ]
