# Generated by Django 5.0 on 2025-07-21 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_remove_productcategory_name_ru'),
        ('home', '0024_ntochka_in_proccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Maxsus'),
        ),
        migrations.AddField(
            model_name='tochkaproducthistory',
            name='is_from_application',
            field=models.BooleanField(default=False, verbose_name='Ariza tomonidan yaratilgan'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('application_type', models.CharField(choices=[('for_close', 'Yopish uchun'), ('for_open', 'Yaratish uchun')], max_length=15, verbose_name='Ariza turi')),
                ('products', models.JSONField(default=list, verbose_name='Mahsulotlar')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Tekshirilgan vaqt')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Tekshirilgan')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_applications', to=settings.AUTH_USER_MODEL, verbose_name='Tekshiruvchi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='home.employee', verbose_name='Xodim')),
                ('ntochka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='home.ntochka', verbose_name='Rasta')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='home.perioddate', verbose_name='Davr')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
