# Generated by Django 5.0 on 2025-07-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0024_product_is_special_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AlterModelTable(
            name='application',
            table='application',
        ),
    ]
