# Generated by Django 5.0 on 2025-07-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0025_alter_application_options_alter_application_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochkaproduct',
            name='miqdor',
            field=models.FloatField(default=0.0, verbose_name='Birlik miqdori'),
        ),
    ]
