# Generated by Django 5.0 on 2025-07-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0026_tochkaproduct_miqdor'),
        ('home', '0024_ntochka_in_proccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ntochkas',
            field=models.ManyToManyField(related_name='huds', to='home.ntochka', verbose_name='rastalar'),
        ),
    ]
