# Generated by Django 5.0 on 2025-07-21 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0027_application_ntochkas'),
        ('home', '0024_ntochka_in_proccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ntochka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='home.ntochka', verbose_name='Rasta'),
        ),
        migrations.AlterField(
            model_name='application',
            name='products',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Mahsulotlar'),
        ),
    ]
