# Generated by Django 5.0 on 2025-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0028_alter_application_ntochka_alter_application_products'),
        ('home', '0024_ntochka_in_proccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ntochkas',
            field=models.ManyToManyField(blank=True, null=True, related_name='huds', to='home.ntochka', verbose_name='rastalar'),
        ),
    ]
