# Generated by Django 5.0 on 2025-07-22 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0029_alter_application_ntochkas'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hbhd',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='HBHD   (1-B, 2-D, 3-HB, 4-HD)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_index',
            field=models.BooleanField(default=False, verbose_name='Indeks'),
        ),
    ]
