# Generated by Django 5.0 on 2025-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0030_product_hbhd_product_is_index'),
        ('home', '0024_ntochka_in_proccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ntochkas',
            field=models.ManyToManyField(blank=True, related_name='huds', to='home.ntochka', verbose_name='rastalar'),
        ),
    ]
