# Generated by Django 5.0 on 2025-07-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0024_product_is_special_tochkaproduct_miqdor_and_more'),
        ('form', '0031_alter_application_ntochkas'),
    ]

    operations = [
    ]
