# Generated by Django 5.0 on 2025-07-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0031_alter_application_ntochkas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochkaproduct',
            name='is_weekly',
            field=models.BooleanField(default=False, verbose_name='Haftalik'),
        ),
    ]
