# Generated by Django 5.0 on 2025-07-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0032_tochkaproduct_is_weekly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_weekly',
        ),
        migrations.AddField(
            model_name='product',
            name='weekly',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Haftalik'),
        ),
    ]
