# Generated by Django 5.0 on 2025-07-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0033_remove_product_is_weekly_product_weekly'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tochkaproduct',
            unique_together=set(),
        ),
    ]
