# Generated by Django 5.0 on 2025-07-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0034_alter_tochkaproduct_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='rasfas',
            field=models.PositiveIntegerField(default=1, verbose_name='Rasfas'),
        ),
    ]
