# Generated by Django 5.0 on 2025-07-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0035_alter_productcategory_rasfas'),
        ('home', '0027_tochka_in_proccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tochka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.tochka', verbose_name='Obyekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='tochkas',
            field=models.ManyToManyField(blank=True, related_name='applications', to='home.tochka', verbose_name='Obyektlar'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('for_close_rasta', 'Rasta yopish uchun'), ('for_open_rasta', 'Rasta yaratish uchun'), ('for_close_obyekt', 'Obyekt yopish uchun'), ('for_open_obyekt', 'Obyekt yaratish uchun')], max_length=20, verbose_name='Ariza turi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ntochkas',
            field=models.ManyToManyField(blank=True, to='home.ntochka', verbose_name='Rastalari'),
        ),
    ]
