# Generated by Django 5.0 on 2025-07-25 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0036_application_tochka_application_tochkas_and_more'),
        ('home', '0027_tochka_in_proccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tochka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tochka', verbose_name='Obyekt'),
        ),
    ]
