# Generated by Django 5.0 on 2025-07-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0037_alter_application_tochka'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='detail',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="To'liq mahsulotlar"),
        ),
    ]
