# Generated by Django 5.0 on 2025-07-25 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0038_application_detail'),
        ('home', '0027_tochka_in_proccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['employee', '-created_at'], name='application_employe_18453e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_type', 'is_checked'], name='application_applica_3bea8c_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['period', 'is_active'], name='application_period__91d83f_idx'),
        ),
    ]
