# Generated by Django 5.0 on 2025-07-28 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0039_application_application_employe_18453e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochkaproducthistory',
            name='tochka_product',
            field=models.ForeignKey(default=1913, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='form.tochkaproduct', verbose_name='Rasta mahsulot'),
            preserve_default=False,
        ),
    ]
