# Generated by Django 5.0 on 2025-07-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0040_tochkaproducthistory_tochka_product'),
        ('home', '0029_tochka_pinfl'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tochkaproducthistory',
            unique_together={('tochka_product', 'period')},
        ),
    ]
