# Generated by Django 5.0 on 2025-07-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0041_alter_tochkaproducthistory_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tochkaproducthistory',
            name='alternative_for',
        ),
    ]
