# Generated by Django 5.0 on 2025-07-28 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0042_remove_tochkaproducthistory_alternative_for'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tochkaproducthistory',
            options={'verbose_name': 'Mahsulot marx tarixi', 'verbose_name_plural': 'Mahsulot narxlari tarixi'},
        ),
        migrations.RemoveField(
            model_name='tochkaproducthistory',
            name='hudud',
        ),
        migrations.RemoveField(
            model_name='tochkaproducthistory',
            name='ntochka',
        ),
        migrations.RemoveField(
            model_name='tochkaproducthistory',
            name='product',
        ),
        migrations.AddField(
            model_name='tochkaproducthistory',
            name='alternative_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.tochkaproduct', verbose_name='Alternativ Product'),
        ),
    ]
