# Generated by Django 5.0 on 2025-07-28 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0043_alter_tochkaproducthistory_options_and_more'),
        ('home', '0029_tochka_pinfl'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochkaproducthistory',
            name='hudud',
            field=models.ForeignKey(default=88, on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='home.tochka', verbose_name='Obyekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tochkaproducthistory',
            name='ntochka',
            field=models.ForeignKey(default=142, on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='home.ntochka', verbose_name='Rasta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tochkaproducthistory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='form.product', verbose_name='Mahsulot'),
            preserve_default=False,
        ),
    ]
