# Generated by Django 5.0 on 2025-09-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0045_product_weekly_type_productcategory_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shtrix kodi'),
        ),
    ]
