# Generated by Django 5.0 on 2025-09-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0046_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mahsulot kodi'),
        ),
    ]
