# Generated by Django 5.0 on 2025-11-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0047_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='product_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'mahsulot'), (2, 'no mahsulot'), (3, 'xizmat')], default=1, verbose_name='Mahsulot turi'),
        ),
    ]
