# Generated by Django 5.0 on 2025-12-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0048_alter_productcategory_product_type'),
        ('home', '0035_district_district_region__5baebe_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tochkaproduct',
            options={'ordering': ['-id'], 'verbose_name': 'Rasta mahsulot', 'verbose_name_plural': 'Rasta mahsulotlari'},
        ),
        migrations.AddIndex(
            model_name='tochkaproduct',
            index=models.Index(fields=['product', 'ntochka'], name='rasta_produ_product_437041_idx'),
        ),
        migrations.AddIndex(
            model_name='tochkaproduct',
            index=models.Index(fields=['hudud'], name='rasta_produ_hudud_i_4abd93_idx'),
        ),
        migrations.AddIndex(
            model_name='tochkaproduct',
            index=models.Index(fields=['-id'], name='rasta_produ_id_606c43_idx'),
        ),
        migrations.AddIndex(
            model_name='tochkaproduct',
            index=models.Index(fields=['is_udalen', 'is_active'], name='rasta_produ_is_udal_652701_idx'),
        ),
        migrations.AddIndex(
            model_name='tochkaproducthistory',
            index=models.Index(fields=['-id'], name='product_his_id_451d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='tochkaproducthistory',
            index=models.Index(fields=['employee', '-created_at'], name='product_his_employe_6dca38_idx'),
        ),
        migrations.AddIndex(
            model_name='tochkaproducthistory',
            index=models.Index(fields=['status', 'is_active', 'is_checked'], name='product_his_status_1dac67_idx'),
        ),
        migrations.AddIndex(
            model_name='tochkaproducthistory',
            index=models.Index(fields=['period', 'hudud'], name='product_his_period__33b3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='tochkaproducthistory',
            index=models.Index(fields=['created_at'], name='product_his_created_00b8af_idx'),
        ),
    ]
