# Generated by Django 5.0 on 2025-12-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0049_alter_tochkaproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tochkaproduct',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tochkaproducthistory',
            options={'verbose_name': 'Mahsulot narxlari tarixi', 'verbose_name_plural': 'Mahsulot narxlari tarixi'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='union',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Birlashtirish'),
        ),
    ]
