# Generated by Django 5.0 on 2025-12-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0050_alter_tochkaproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='union',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Birligi'),
        ),
    ]
