# Generated by Django 5.0 on 2025-12-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0051_alter_productcategory_union'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Faol'),
        ),
    ]
