# Generated by Django 5.0 on 2025-12-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0052_alter_application_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
    ]
