# Generated by Django 5.0 on 2025-12-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0053_alter_application_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochkaproducthistory',
            name='is_from_period_create',
            field=models.BooleanField(default=False, verbose_name='Davr yaratishda yaratilgan'),
        ),
    ]
