# Generated by Django 5.0 on 2025-07-02 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tumanning nomi')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Tumanning kodi')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Davrning nomi')),
                ('period_type', models.CharField(choices=[('weekly', 'Haftalik'), ('monthly', 'Oylik')], default='monthly', max_length=50, verbose_name='Davr turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Davr',
                'verbose_name_plural': 'Davrlar',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Viloyatning nomi')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Viloyatning kodi')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.Sh')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Login')),
                ('password', models.CharField(max_length=100, verbose_name='Parol')),
                ('status', models.FloatField(default=1.0, verbose_name='Status')),
                ('permission1', models.BooleanField(default=True, verbose_name='Ruxsat 1')),
                ('permission2', models.BooleanField(default=True, verbose_name='Ruxsat 2')),
                ('permission3', models.BooleanField(default=True, verbose_name='Ruxsat 3')),
                ('permission4', models.BooleanField(default=False, verbose_name='Ruxsat 4')),
                ('permission5', models.BooleanField(default=False, verbose_name='Ruxsat 5')),
                ('permission_plov', models.BooleanField(default=False, verbose_name='Palov uchun ruxsat')),
                ('gps_permission', models.BooleanField(default=True, verbose_name='GPS ruxsat')),
                ('lang', models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Rus')], default='uz', max_length=10, verbose_name='Til')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='home.district', verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='PeriodDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('date', models.DateField(verbose_name='Sana')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_dates', to='home.period', verbose_name='Davr')),
            ],
            options={
                'verbose_name': 'Davr sanasi',
                'verbose_name_plural': 'Davr sanalari',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='home.region', verbose_name='Viloyat'),
        ),
        migrations.CreateModel(
            name='Tochka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tochkaning nomi')),
                ('inn', models.CharField(blank=True, default=0, max_length=20, verbose_name='INN kodi')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('plan', models.IntegerField(default=0, verbose_name='Plan id')),
                ('lat', models.FloatField(default=0.0, verbose_name='Lat')),
                ('lon', models.FloatField(default=0.0, verbose_name='Lon')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tochkas', to='home.district', verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Tochka',
                'verbose_name_plural': 'Tochkalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PeriodTochka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('plan', models.IntegerField(default=0, verbose_name='Plan')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_tochkas', to='home.period', verbose_name='Davr')),
                ('tochka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_tochkas', to='home.tochka', verbose_name='Tochka')),
            ],
            options={
                'verbose_name': 'Davr Tochka',
                'verbose_name_plural': 'Davr Tochkalari',
                'ordering': ['period__name', 'tochka__name'],
                'unique_together': {('period', 'tochka')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeTochka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tochkas', to='home.employee', verbose_name='Xodim')),
                ('tochka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tochkas', to='home.tochka', verbose_name='Tochka')),
            ],
            options={
                'verbose_name': 'Xodimning Tochka',
                'verbose_name_plural': 'Xodimning Tochkalari',
                'unique_together': {('employee', 'tochka')},
            },
        ),
    ]
