# Generated by Django 5.0 on 2025-07-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Tumanning kodi'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('code', 'region')},
        ),
    ]
