# Generated by Django 5.0 on 2025-07-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_district_code_alter_district_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tumanning nomi'),
        ),
    ]
