# Generated by Django 5.0 on 2025-07-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_district_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochka',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.DeleteModel(
            name='PeriodTochka',
        ),
    ]
