# Generated by Django 5.0 on 2025-07-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tochka_is_active_delete_periodtochka'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 2'),
        ),
    ]
