# Generated by Django 5.0 on 2025-07-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_employee_phone1_employee_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 1  (mtel)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 2  (otel)'),
        ),
    ]
