# Generated by Django 5.0 on 2025-07-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_ntochka'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochka',
            name='employee',
            field=models.ForeignKey(default=465, on_delete=django.db.models.deletion.CASCADE, related_name='tochkas', to='home.employee', verbose_name='Xodim'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmployeeTochka',
        ),
    ]
