# Generated by Django 5.0 on 2025-07-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_tochka_employee_delete_employeetochka'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntochka',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
    ]
