# Generated by Django 5.0 on 2025-07-08 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_ntochka_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntochka',
            name='hudud',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='ntochkas', to='home.tochka', verbose_name='Tochka'),
            preserve_default=False,
        ),
    ]
