# Generated by Django 5.0 on 2025-07-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_ntochka_hudud'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='uuid',
            field=models.UUIDField(default=1, unique=True, verbose_name='UUID'),
            preserve_default=False,
        ),
    ]
