# Generated by Django 5.0 on 2025-07-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_employee_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='uuid',
            field=models.UUIDField(auto_created=True, unique=True, verbose_name='UUID'),
        ),
    ]
