# Generated by Django 5.0 on 2025-07-11 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_employee_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochka',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='tochka',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tochkaning nomi'),
        ),
    ]
