# Generated by Django 5.0 on 2025-07-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_tochka_uuid_alter_tochka_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochka',
            name='icon',
            field=models.CharField(choices=[('icon1', 'Icon 1'), ('icon2', 'Icon 2'), ('icon3', 'Icon 3'), ('icon4', 'Icon 4')], default='icon1', max_length=10, verbose_name='Icon'),
        ),
    ]
