# Generated by Django 5.0 on 2025-07-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_tochka_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tochka',
            name='icon',
            field=models.CharField(choices=[('restaurant', 'Kafe / Oshxona / Stolovaya'), ('water', 'Santexnika / Suv / Kommunal'), ('flash', 'Elektrik'), ('shirt', 'Kiyim / Kosmetika / Tikuv'), ('bed', 'Mebel'), ('cart', 'Do‘kon'), ('eye', 'Optika'), ('leaf', 'Gullar / Qishloq xo‘jaligi'), ('construct', 'Ta’mirlash / Bo‘yash'), ('home', 'Kvartira / Uy'), ('briefcase', 'Xizmat / Sluzhba'), ('storefront', 'Market / Magazin / Savdo markazi'), ('car', 'Avto / Servis / Zapchast'), ('tv', 'Texnika / Media'), ('school', 'Maktab / O‘quv markazi'), ('person', 'Kasanachi / Uyda ishlovchi'), ('people', 'Xususiy shaxs / MCHJ'), ('location', 'Boshqa / Default')], default='location', max_length=10, verbose_name='Icon'),
        ),
    ]
