# Generated by Django 5.0 on 2025-07-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_tochka_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tochka',
            name='icon',
            field=models.CharField(choices=[('restaurant', 'Kafe oshxona'), ('water', 'Suv xizmatlari'), ('flash', 'Elektr ustasi'), ('shirt', 'Kiyim do‘koni'), ('bed', 'Uy mebellari'), ('cart', 'Mahsulot do‘koni'), ('eye', 'Ko‘zoynak optika'), ('leaf', 'Qishloq xo‘jaligi'), ('construct', 'Ta’mirlash ishlari'), ('home', 'Oilaviy Biznes'), ('briefcase', 'Xizmat joyi'), ('storefront', 'Savdo markazi'), ('car', 'Avto do‘kon'), ('tv', 'Elektronika texnika'), ('school', 'O‘quv markazi'), ('person', 'Uyda ishlovchi'), ('people', 'Xususiy shaxs'), ('nutrition', 'Oziq ovqat mahsulotlari'), ('location', 'Boshqa')], default='nutrition', max_length=10, verbose_name='Icon'),
        ),
    ]
