# Generated by Django 5.0 on 2025-07-11 15:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_tochka_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntochka',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
    ]
