# Generated by Django 5.0 on 2025-07-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_ntochka_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ntochka',
            options={'ordering': ['name'], 'verbose_name': 'Rasta', 'verbose_name_plural': 'Rastalar'},
        ),
        migrations.AlterModelOptions(
            name='tochka',
            options={'ordering': ['name'], 'verbose_name': 'Obyekt', 'verbose_name_plural': 'Obyektlar'},
        ),
        migrations.AlterModelTable(
            name='ntochka',
            table='home_rasta',
        ),
        migrations.AlterModelTable(
            name='tochka',
            table='home_obyekt',
        ),
    ]
