# Generated by Django 5.0 on 2025-07-15 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_ntochka_options_alter_tochka_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntochka',
            name='hudud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ntochkas', to='home.tochka', verbose_name='Obyekt'),
        ),
        migrations.AlterField(
            model_name='ntochka',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Rasta nomi'),
        ),
        migrations.AlterField(
            model_name='tochka',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Obyekt nomi'),
        ),
    ]
