# Generated by Django 5.0 on 2025-07-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_ntochka_hudud_alter_ntochka_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table='district',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='ntochka',
            table='rasta',
        ),
        migrations.AlterModelTable(
            name='period',
            table='period',
        ),
        migrations.AlterModelTable(
            name='perioddate',
            table='period_date',
        ),
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
        migrations.AlterModelTable(
            name='tochka',
            table='obyekt',
        ),
    ]
