# Generated by Django 5.0 on 2025-07-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_district_table_alter_employee_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='PINFL'),
        ),
    ]
