# Generated by Django 5.0 on 2025-07-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_employee_pinfl'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochka',
            name='code',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Obyekt kodi'),
            preserve_default=False,
        ),
    ]
