# Generated by Django 5.0 on 2025-07-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_ntochka_in_proccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntochka',
            name='is_weekly',
            field=models.BooleanField(default=False, verbose_name='Haftalik'),
        ),
        migrations.AddField(
            model_name='tochka',
            name='is_weekly',
            field=models.BooleanField(default=False, verbose_name='Haftalik'),
        ),
    ]
