# Generated by Django 5.0 on 2025-07-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_ntochka_is_weekly_tochka_is_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntochka',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Rasta kodi'),
            preserve_default=False,
        ),
    ]
