# Generated by Django 5.0 on 2025-07-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_ntochka_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochka',
            name='in_proccess',
            field=models.BooleanField(default=False, verbose_name='Ariza orqali yaratilgan'),
        ),
    ]
