# Generated by Django 5.0 on 2025-07-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_tochka_in_proccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntochka',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Rasta kodi'),
        ),
    ]
