# Generated by Django 5.0 on 2025-07-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_ntochka_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochka',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='PINFL'),
        ),
    ]
