# Generated by Django 5.0 on 2025-07-30 06:21

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_tochka_pinfl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tochka',
            name='is_weekly',
        ),
        migrations.AddField(
            model_name='ntochka',
            name='product_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'mahsulot'), ('2', 'no mahsulot'), ('3', 'xizmat')], default=['1'], max_length=10, verbose_name='Mahsulot turi'),
        ),
        migrations.AddField(
            model_name='ntochka',
            name='weekly_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'haftalik'), (2, 'oylik'), (3, 'bari')], default=1, verbose_name='Haftalik turi'),
        ),
        migrations.AddField(
            model_name='tochka',
            name='product_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'mahsulot'), ('2', 'no mahsulot'), ('3', 'xizmat')], default=['1'], max_length=10, verbose_name='Mahsulot turi'),
        ),
        migrations.AddField(
            model_name='tochka',
            name='weekly_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'haftalik'), (2, 'oylik'), (3, 'bari')], default=1, verbose_name='Haftalik turi'),
        ),
    ]
