# Generated by Django 5.0 on 2025-08-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_tochka_is_weekly_ntochka_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochka',
            name='is_inDSQ',
            field=models.BooleanField(default=False, verbose_name='DSQda mavjud'),
        ),
    ]
