# Generated by Django 5.0 on 2025-09-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_tochka_is_indsq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tochka',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Obyekt nomi'),
        ),
    ]
