# Generated by Django 5.0 on 2025-09-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_tochka_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='PINFL'),
        ),
    ]
