# Generated by Django 5.0 on 2025-12-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_employee_pinfl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntochka',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Rasta nomi'),
        ),
    ]
