# Generated by Django 5.0 on 2025-12-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_ntochka_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['region', 'name'], name='district_region__5baebe_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['district', 'status'], name='employee_distric_228108_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['full_name'], name='employee_full_na_b33199_idx'),
        ),
        migrations.AddIndex(
            model_name='ntochka',
            index=models.Index(fields=['hudud', 'is_active'], name='rasta_hudud_i_363e25_idx'),
        ),
        migrations.AddIndex(
            model_name='ntochka',
            index=models.Index(fields=['-id'], name='rasta_id_6e0ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='tochka',
            index=models.Index(fields=['district', 'is_active'], name='obyekt_distric_ae51b5_idx'),
        ),
        migrations.AddIndex(
            model_name='tochka',
            index=models.Index(fields=['employee'], name='obyekt_employe_21c20e_idx'),
        ),
        migrations.AddIndex(
            model_name='tochka',
            index=models.Index(fields=['-id'], name='obyekt_id_f4c6d1_idx'),
        ),
    ]
