# Generated by Django 5.0 on 2025-12-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_district_district_region__5baebe_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntochka',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='tochka',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Faol'),
        ),
    ]
