<<<<<<< HEAD
# Generated by Django 5.0 on 2025-12-11 13:49
=======
# Generated by Django 5.0 on 2025-12-11 12:28
>>>>>>> 11dcc481c1faab336bc965da14a901011a7c9767

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_ntochka_is_active_alter_tochka_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntochka',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='tochka',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
    ]
