# Generated by Django 5.0 on 2025-07-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KoboForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=100, unique=True, verbose_name='Kobo form id')),
                ('name', models.CharField(max_length=255, verbose_name='Form nomi')),
                ('api_token', models.CharField(max_length=255, verbose_name='API token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
        ),
    ]
