# Generated by Django 5.0 on 2025-09-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanshetExcelImport',
            fields=[
            ],
            options={
                'verbose_name': '📥 Excel import (Planshet)',
                'verbose_name_plural': '📥 Excel import (Planshet)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.koboform',),
        ),
    ]
