# Generated by Django 5.0 on 2025-09-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_planshetexcelimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='HududImportProxy',
            fields=[
            ],
            options={
                'verbose_name': '📥 Hududlar (JSON import)',
                'verbose_name_plural': '📥 Hududlar (JSON import)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.koboform',),
        ),
    ]
